In [16]:
import numpy as np

u = np.array([1,2,3,4])
v = np.array([2,3,0,1])

print(u.shape, v.shape)
print(u, v)

(4,) (4,)
[1 2 3 4] [2 3 0 1]


In [17]:
print(u*v, u.dot(v)) # Hadamard product and vector dot product

[2 6 0 4] 12


In [18]:
# next change u into column vector cu
cu = u.reshape(4,1)
print(cu.shape, "\n")
print(cu)

(4, 1) 

[[1]
 [2]
 [3]
 [4]]


In [19]:
print(cu * v) # Hadamard product

[[ 2  3  0  1]
 [ 4  6  0  2]
 [ 6  9  0  3]
 [ 8 12  0  4]]


In [20]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[2, 1], [-2, 3]])

print(m1, "\n\n", m2)

[[1 2]
 [3 4]] 

 [[ 2  1]
 [-2  3]]


In [21]:
# Elementwise multiplication and matrix multiplication
print(m1*m2,"\n\n", m1.dot(m2))

[[ 2  2]
 [-6 12]] 

 [[-2  7]
 [-2 15]]


In [22]:
# Define the matrix 'a'
a = np.array([[1, 0, 0, 0],
              [0, 1, 1, 0],
              [0, 0, 1, 2]])

In [23]:
print(a.dot(u), "\n")
print(a.dot(cu))

[ 1  5 11] 

[[ 1]
 [ 5]
 [11]]


In [24]:
b = np.array([[3,1], [2,2],[1,3], [1,11]])
print(a,"\n\n\n", b)

[[1 0 0 0]
 [0 1 1 0]
 [0 0 1 2]] 


 [[ 3  1]
 [ 2  2]
 [ 1  3]
 [ 1 11]]


In [25]:
print(a.dot(b))

[[ 3  1]
 [ 3  5]
 [ 3 25]]


In [26]:
# Transpose of a
a.T

array([[1, 0, 0],
       [0, 1, 0],
       [0, 1, 1],
       [0, 0, 2]])

In [27]:
print(a.shape, a.T.shape)

(3, 4) (4, 3)


In [28]:
print(a)

[[1 0 0 0]
 [0 1 1 0]
 [0 0 1 2]]


In [29]:
u.dot(a.T)

array([ 1,  5, 11])

In [30]:
# old fashioned code to multiply each element of a by 2  
(m,n) = a.shape  
c = np.zeros((m,n), "int32")  
print (c) 

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [31]:
for i in range (m):  
    for j in range (n):  
        c[i,j] = a[i,j]*2  
print (c) 

[[2 0 0 0]
 [0 2 2 0]
 [0 0 2 4]]


In [32]:
# easier way  
print (a*2)  

[[2 0 0 0]
 [0 2 2 0]
 [0 0 2 4]]
