In [1]:
import numpy as np
v1 = np.array([4,2,6,1])
v2 = np.random.rand(4)
print(v1, "\n", v2)

[4 2 6 1] 
 [0.85437228 0.8551177  0.12765822 0.76164305]


In [3]:
w = [x**2 for x in v1]
w

[16, 4, 36, 1]

In [5]:
v1.shape

(4,)

In [7]:
n, = v1.shape
print(n)
v3 = np.zeros(n)
print(v3)
for j in range(n):
    v3[j] = v1[j]**2
print(v3)
v4 = v1**2
print(v4)

4
[0. 0. 0. 0.]
[16.  4. 36.  1.]
[16  4 36  1]
